### ISSUE TITLE
Problem with the showing number of voters

### ISSUE THREAD

**Issue by VadymEverstake** [sudoblockio/icon-tracker#69]
### Issue type 

- [ ] Bug 

### Issue Description
I have a question regarding the Voters section. At the end of October, this number for Everstake jumped from approximately 930 to 2K+ in a day and stayed like this ever since. This jump occurred for other P-Reps too. Also for most of the voters shows that they stake or even hold 0 ICX. Do you know why did this happen? 
### Steps to Reproduce the Problem / Desired Outcome 

  1. 
  2.

**Comment by robcxyz** [comment]
Fixed
