### ISSUE TITLE
Status Page has NET::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by CyrusVorwald** [sudoblockio/icon-tracker#74]
### Issue type 

- Bug 

### Issue Description

https://status.icon.sudoblock.io/ connection insecure due to NET::ERR_CERT_COMMON_NAME_INVALID error

Description

### Link / Screenshot

<img width="702" alt="image" src="https://user-images.githubusercontent.com/90732384/225411369-cd07114b-e52c-4b4b-b6b5-2388adadce10.png">

https://status.icon.sudoblock.io/

**Comment by robcxyz** [comment]
Wrong link. Updated https://tracker.status.icon.community/
