### ISSUE TITLE
Link to Transformer and Go-API docs invalid

### ISSUE THREAD

**Issue by CyrusVorwald** [sudoblockio/icon-tracker#75]
### Issue type 

- [X] Bug 
- [ ] Feature request

### Issue Description

[//]: # (Description of the issue)

Links to Transformer and Go-API API docs invalid at https://github.com/sudoblockio/icon-tracker#domains

Both link to https://tracker.icon.community/api/v1/metrics/docs which states Cannot GET /api/v1/metrics/docs

<img width="472" alt="image" src="https://user-images.githubusercontent.com/90732384/225412129-2f6ba798-cc76-401b-9f5c-e2c8fc241dd6.png">

**Comment by robcxyz** [comment]
Should not have been there. Transformer doesn't have api docs and metrics has been deprecated
